services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - /app/.venv
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://aitrainer:aitrainerpass@mongo:27017/aitrainerdb?authSource=admin
      - QDRANT_HOST=qdrant



    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongo
      - qdrant
    networks:
      - aitrainer-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - aitrainer-network

  mongo:
    image: docker.io/library/mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-aitrainer}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-aitrainerpass}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-aitrainerdb}
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - aitrainer-network

  mongo-express:
    image: docker.io/library/mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME:-aitrainer}:${MONGO_INITDB_ROOT_PASSWORD:-aitrainerpass}@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: "true"
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    depends_on:
      - mongo
    networks:
      - aitrainer-network

  qdrant:
    image: docker.io/qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - aitrainer-network

volumes:
  mongodata:
  qdrant_data:


networks:
  aitrainer-network:
    driver: bridge
